<a href="https://colab.research.google.com/github/Sahilmandalwar/Scientific_computing_codes/blob/main/central_finite_difference_differential_equation_second_order.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import math

**Differential Equation term must be:**

 *y`` + p(x)y` + q(x)y = r(x)*

 y(a) = A ,  y(b) = B where x belongs to [a,b]



  Note :
  1. p(x) is denoted as p_x(x)
  2. q(x) is denoted as q_x(x)
  3. r(x) is denoted as rhs
  4. a_val is A
  5. b_val is B
  6. res_matrix is resultant matrix





In [ ]:
def p_x(x):   # define p(x) here
  return 0

def q_x(x):   # define q(x) here
  return -1


In [ ]:
def make_matrix(h,a,b,a_val,b_val,rhs):
  x = a
  rows = int((b - a) / h) - 1
  A_array = []
  for row in range(rows):
    temp = []
    for i in range(rows):
      if(i == row - 1):
        temp.append((1/h**2 - p_x((row + 1)*h + x)/2*h))
      elif ( i == row):
        temp.append(q_x((row + 1)*h + x) - 2/h**2)
      elif (i ==  row+1):
        temp.append((1/h**2 + p_x((row + 1)*h + x)/2*h))
      else:
        temp.append(0)
    A_array.append(temp)

  A_matrix = np.matrix(A_array)

  B_array = []
  for row in range(rows):
    if(row == 0):
      B_array.append(rhs - (1/h**2 - p_x((row + 1)*h + x)/2*h) * a_val)
    elif (row == rows - 1):
      B_array.append(rhs - (1/h**2 + p_x((row + 1)*h + x)/2*h) * b_val)
    else:
      B_array.append(rhs)

  B_matrix = np.matrix(B_array)

  return A_matrix, B_matrix

In [ ]:
h = 1/3   # step size
a = 0      # initial point
b = 1      # final point
a_val = 0  # y value at initial_point
b_val = math.e - 1 # y value at final_point
rhs = 1    # rhs value

In [ ]:
A,B = make_matrix(h,a,b,a_val,b_val,rhs)

In [ ]:
A

matrix([[-19.,   9.],
        [  9., -19.]])

In [ ]:
B

matrix([[  1.        , -14.46453646]])

In [ ]:
res_matrix = np.matmul(np.linalg.inv(A),B.T)

In [ ]:
res_matrix   # res_matrix is resultant matrix

matrix([[0.39707439],
        [0.94937926]])